import { useEffect, useState } from "react";
import type { AppProps } from "next/app";
import { useRouter } from "next/router";
import Head from "next/head";

import Header from "../components/header/header";
import NavbarFrame from "../components/header/navbarFrame";
import Navbar from "../components/header/navbar";
import Footer from "../components/footer/footer";

import { MovieContextProvider } from "../context/movieData-context";
import { SpinnerContextProvider } from "../context/spinner-context";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
    const router = useRouter();

    const routerHasId = router.query.id ? true : false;

    const type =
        router.asPath === "/"
            ? ""
            : router.asPath.startsWith("/movie")
            ? router.query.type?.toString() || "Trending"
            : router.asPath.startsWith("/tv")
            ? router.query.type?.toString() || "Popular"
            : router.query.type?.toString() || "Popular";

    const mediaType = router.asPath.toLocaleLowerCase().includes("movie")
        ? "movie"
        : router.asPath.toLocaleLowerCase().includes("tv")
        ? "tv"
        : router.asPath.toLocaleLowerCase().includes("people")
        ? "people"
        : "home";

    return (
        <div>
            <Head>
                <title>IMDB Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <SpinnerContextProvider>
                <MovieContextProvider>
                    {/* {!router.query.id && <Header />} */}
                    <Header />
                    {routerHasId ||
                    router.pathname === "/movie" ||
                    router.pathname === "/tv" ? (
                        <></>
                    ) : (
                        <Navbar type={type} mediaType={mediaType} />
                    )}
                    <Component {...pageProps} />
                </MovieContextProvider>
            </SpinnerContextProvider>
        </div>
    );
}

export default MyApp;
