/****************************************************************************/
/***************************ForbiddenMedia*********************************/
/****************************************************************************/
export function ForbiddenMedia(
    mediaData: {
        backdrop_path: string;
        id: string;
        title: string;
        original_language: string;
        original_title: string;
        original_name: string;
        overview: string;
        poster_path: string;
        media_type: string;
        release_date: string;
        first_air_date: string;
        vote_average: number;
        vote_count: number;
        name: string;
    }[]
) {
    mediaData.forEach((media, index) => {
        const name = media?.name?.toLowerCase();
        const original_name = media?.original_name?.toLowerCase();
        const title = media?.title?.toLowerCase();
        const original_title = media?.original_title?.toLowerCase();

        // Removing +18content
        if (
            name?.includes("sex") ||
            original_name?.includes("sex") ||
            title?.includes("sex") ||
            original_title?.includes("sex") ||
            name?.includes("horny") ||
            original_name?.includes("horny") ||
            title?.includes("horny") ||
            original_title?.includes("horny") ||
            name?.includes("tit") ||
            original_name?.includes("tit") ||
            title?.includes("tit") ||
            original_title?.includes("tit") ||
            name?.includes("boob") ||
            original_name?.includes("boob") ||
            title?.includes("boob") ||
            original_title?.includes("boob") ||
            name?.includes("hentai") ||
            original_name?.includes("hentai") ||
            title?.includes("hentai") ||
            original_title?.includes("hentai") ||
            name?.includes("fuck") ||
            original_name?.includes("fuck") ||
            title?.includes("fuck") ||
            original_title?.includes("fuck") ||
            name?.includes("porn") ||
            original_name?.includes("porn") ||
            title?.includes("porn") ||
            original_title?.includes("porn") ||
            name?.includes("gay") ||
            original_name?.includes("gay") ||
            title?.includes("gay") ||
            original_title?.includes("gay") ||
            name?.includes("lesbian") ||
            original_name?.includes("lesbian") ||
            title?.includes("lesbian") ||
            original_title?.includes("lesbian") ||
            name?.includes("ass") ||
            original_name?.includes("ass") ||
            title?.includes("ass") ||
            original_title?.includes("ass") ||
            name?.includes("orgasm") ||
            original_name?.includes("orgasm") ||
            title?.includes("orgasm") ||
            original_title?.includes("orgasm") ||
            name?.includes("virgin") ||
            original_name?.includes("virgin") ||
            title?.includes("virgin") ||
            original_title?.includes("virgin") ||
            name?.includes("18") ||
            original_name?.includes("18") ||
            title?.includes("18") ||
            original_title?.includes("18") ||
            name?.includes("16") ||
            original_name?.includes("16") ||
            title?.includes("16") ||
            original_title?.includes("16") ||
            name?.includes("transgender") ||
            original_name?.includes("transgender") ||
            title?.includes("transgender") ||
            original_title?.includes("transgender") ||
            name?.includes("mature") ||
            original_name?.includes("mature") ||
            title?.includes("mature") ||
            original_title?.includes("mature") ||
            name?.includes("milf") ||
            original_name?.includes("milf") ||
            title?.includes("milf") ||
            original_title?.includes("milf") ||
            name?.includes("orgy") ||
            original_name?.includes("orgy") ||
            title?.includes("orgy") ||
            original_title?.includes("orgy") ||
            name?.includes("cosplay") ||
            original_name?.includes("cosplay") ||
            title?.includes("cosplay") ||
            original_title?.includes("cosplay") ||
            name?.includes("squirt") ||
            original_name?.includes("squirt") ||
            title?.includes("squirt") ||
            original_title?.includes("squirt") ||
            name?.includes("brunette") ||
            original_name?.includes("brunette") ||
            title?.includes("brunette") ||
            original_title?.includes("brunette") ||
            name?.includes("handjob") ||
            original_name?.includes("handjob") ||
            title?.includes("handjob") ||
            original_title?.includes("handjob") ||
            name?.includes("cum") ||
            original_name?.includes("cum") ||
            title?.includes("cum") ||
            original_title?.includes("cum") ||
            name?.includes("blowjob") ||
            original_name?.includes("blowjob") ||
            title?.includes("blowjob") ||
            original_title?.includes("blowjob") ||
            name?.includes("hardcore") ||
            original_name?.includes("hardcore") ||
            title?.includes("hardcore") ||
            original_title?.includes("hardcore") ||
            name?.includes("tatto") ||
            original_name?.includes("tatto") ||
            title?.includes("tatto") ||
            original_title?.includes("tatto") ||
            name?.includes("pussy") ||
            original_name?.includes("pussy") ||
            title?.includes("pussy") ||
            original_title?.includes("pussy") ||
            name?.includes("fisting") ||
            original_name?.includes("fisting") ||
            title?.includes("fisting") ||
            original_title?.includes("fisting") ||
            name?.includes("strap") ||
            original_name?.includes("strap") ||
            title?.includes("strap") ||
            original_title?.includes("strap") ||
            name?.includes("creampie") ||
            original_name?.includes("creampie") ||
            title?.includes("creampie") ||
            original_title?.includes("creampie") ||
            name?.includes("gangbang") ||
            original_name?.includes("gangbang") ||
            title?.includes("gangbang") ||
            original_title?.includes("gangbang") ||
            name?.includes("female") ||
            original_name?.includes("female") ||
            title?.includes("female") ||
            original_title?.includes("female") ||
            name?.includes("threesome") ||
            original_name?.includes("threesome") ||
            title?.includes("threesome") ||
            original_title?.includes("threesome") ||
            name?.includes("step") ||
            original_name?.includes("step") ||
            title?.includes("step") ||
            original_title?.includes("step") ||
            name?.includes("vintage") ||
            original_name?.includes("vintage") ||
            title?.includes("vintage") ||
            original_title?.includes("vintage") ||
            name?.includes("beach") ||
            original_name?.includes("beach") ||
            title?.includes("beach") ||
            original_title?.includes("beach") ||
            name?.includes("massage") ||
            original_name?.includes("massage") ||
            title?.includes("massage") ||
            original_title?.includes("massage") ||
            name?.includes("love") ||
            original_name?.includes("love") ||
            title?.includes("love") ||
            original_title?.includes("love") ||
            name?.includes("tight") ||
            original_name?.includes("tight") ||
            title?.includes("tight") ||
            original_title?.includes("tight") ||
            name?.includes("feeling") ||
            original_name?.includes("feeling") ||
            title?.includes("feeling") ||
            original_title?.includes("feeling") ||
            name?.includes("heart") ||
            original_name?.includes("heart") ||
            title?.includes("heart") ||
            original_title?.includes("heart") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("pretty") ||
            original_name?.includes("pretty") ||
            title?.includes("pretty") ||
            original_title?.includes("pretty") ||
            name?.includes("high school") ||
            original_name?.includes("high school") ||
            title?.includes("high school") ||
            original_title?.includes("high school") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("girl") ||
            original_name?.includes("girl") ||
            title?.includes("girl") ||
            original_title?.includes("girl") ||
            name?.includes("boy") ||
            original_name?.includes("boy") ||
            title?.includes("boy") ||
            original_title?.includes("boy") ||
            name?.includes("friend") ||
            original_name?.includes("friend") ||
            title?.includes("friend") ||
            original_title?.includes("friend") ||
            name?.includes("x") ||
            original_name?.includes("x") ||
            title?.includes("x") ||
            original_title?.includes("x") ||
            name?.includes("fu") ||
            original_name?.includes("fu") ||
            title?.includes("fu") ||
            original_title?.includes("fu") ||
            name?.includes("f*") ||
            original_name?.includes("f*") ||
            title?.includes("f*") ||
            original_title?.includes("f*") ||
            name?.includes("san") ||
            original_name?.includes("san") ||
            title?.includes("san") ||
            original_title?.includes("san") ||
            name?.includes("whore") ||
            original_name?.includes("whore") ||
            title?.includes("whore") ||
            original_title?.includes("whore") ||
            name?.includes("revolver") ||
            original_name?.includes("revolver") ||
            title?.includes("revolver") ||
            original_title?.includes("revolver")
        ) {
            mediaData?.splice(index, 1);
        }
    });
}

/****************************************************************************/
/***************************ForbiddenSearchMedia*********************************/
/****************************************************************************/
export function ForbiddenSearchMedia(
    searchMedia: {
        page: number;
        results: {
            adult: boolean;
            backdrop_path: string;
            genre_ids: number[];
            id: number;
            original_language: string;
            original_title: string;
            overview: string;
            popularity: number;
            poster_path: string;
            release_date: string;
            title: string;
            video: boolean;
            vote_average: number;
            vote_count: number;
            // tv
            first_air_date: string;
            name: string;
            origin_country: string;
            original_name: string;
        }[];
        total_pages: number;
        total_results: number;
    } | null
) {
    searchMedia?.results.forEach((media, index) => {
        const name = media?.name?.toLowerCase();
        const original_name = media?.original_name?.toLowerCase();
        const title = media?.title?.toLowerCase();
        const original_title = media?.original_title?.toLowerCase();

        // Removing +18content
        if (
            name?.includes("sex") ||
            original_name?.includes("sex") ||
            title?.includes("sex") ||
            original_title?.includes("sex") ||
            name?.includes("horny") ||
            original_name?.includes("horny") ||
            title?.includes("horny") ||
            original_title?.includes("horny") ||
            name?.includes("tit") ||
            original_name?.includes("tit") ||
            title?.includes("tit") ||
            original_title?.includes("tit") ||
            name?.includes("boob") ||
            original_name?.includes("boob") ||
            title?.includes("boob") ||
            original_title?.includes("boob") ||
            name?.includes("hentai") ||
            original_name?.includes("hentai") ||
            title?.includes("hentai") ||
            original_title?.includes("hentai") ||
            name?.includes("fuck") ||
            original_name?.includes("fuck") ||
            title?.includes("fuck") ||
            original_title?.includes("fuck") ||
            name?.includes("porn") ||
            original_name?.includes("porn") ||
            title?.includes("porn") ||
            original_title?.includes("porn") ||
            name?.includes("gay") ||
            original_name?.includes("gay") ||
            title?.includes("gay") ||
            original_title?.includes("gay") ||
            name?.includes("lesbian") ||
            original_name?.includes("lesbian") ||
            title?.includes("lesbian") ||
            original_title?.includes("lesbian") ||
            name?.includes("ass") ||
            original_name?.includes("ass") ||
            title?.includes("ass") ||
            original_title?.includes("ass") ||
            name?.includes("orgasm") ||
            original_name?.includes("orgasm") ||
            title?.includes("orgasm") ||
            original_title?.includes("orgasm") ||
            name?.includes("virgin") ||
            original_name?.includes("virgin") ||
            title?.includes("virgin") ||
            original_title?.includes("virgin") ||
            name?.includes("18") ||
            original_name?.includes("18") ||
            title?.includes("18") ||
            original_title?.includes("18") ||
            name?.includes("16") ||
            original_name?.includes("16") ||
            title?.includes("16") ||
            original_title?.includes("16") ||
            name?.includes("transgender") ||
            original_name?.includes("transgender") ||
            title?.includes("transgender") ||
            original_title?.includes("transgender") ||
            name?.includes("mature") ||
            original_name?.includes("mature") ||
            title?.includes("mature") ||
            original_title?.includes("mature") ||
            name?.includes("milf") ||
            original_name?.includes("milf") ||
            title?.includes("milf") ||
            original_title?.includes("milf") ||
            name?.includes("orgy") ||
            original_name?.includes("orgy") ||
            title?.includes("orgy") ||
            original_title?.includes("orgy") ||
            name?.includes("cosplay") ||
            original_name?.includes("cosplay") ||
            title?.includes("cosplay") ||
            original_title?.includes("cosplay") ||
            name?.includes("squirt") ||
            original_name?.includes("squirt") ||
            title?.includes("squirt") ||
            original_title?.includes("squirt") ||
            name?.includes("brunette") ||
            original_name?.includes("brunette") ||
            title?.includes("brunette") ||
            original_title?.includes("brunette") ||
            name?.includes("handjob") ||
            original_name?.includes("handjob") ||
            title?.includes("handjob") ||
            original_title?.includes("handjob") ||
            name?.includes("cum") ||
            original_name?.includes("cum") ||
            title?.includes("cum") ||
            original_title?.includes("cum") ||
            name?.includes("blowjob") ||
            original_name?.includes("blowjob") ||
            title?.includes("blowjob") ||
            original_title?.includes("blowjob") ||
            name?.includes("hardcore") ||
            original_name?.includes("hardcore") ||
            title?.includes("hardcore") ||
            original_title?.includes("hardcore") ||
            name?.includes("tatto") ||
            original_name?.includes("tatto") ||
            title?.includes("tatto") ||
            original_title?.includes("tatto") ||
            name?.includes("pussy") ||
            original_name?.includes("pussy") ||
            title?.includes("pussy") ||
            original_title?.includes("pussy") ||
            name?.includes("fisting") ||
            original_name?.includes("fisting") ||
            title?.includes("fisting") ||
            original_title?.includes("fisting") ||
            name?.includes("strap") ||
            original_name?.includes("strap") ||
            title?.includes("strap") ||
            original_title?.includes("strap") ||
            name?.includes("creampie") ||
            original_name?.includes("creampie") ||
            title?.includes("creampie") ||
            original_title?.includes("creampie") ||
            name?.includes("gangbang") ||
            original_name?.includes("gangbang") ||
            title?.includes("gangbang") ||
            original_title?.includes("gangbang") ||
            name?.includes("female") ||
            original_name?.includes("female") ||
            title?.includes("female") ||
            original_title?.includes("female") ||
            name?.includes("threesome") ||
            original_name?.includes("threesome") ||
            title?.includes("threesome") ||
            original_title?.includes("threesome") ||
            name?.includes("step") ||
            original_name?.includes("step") ||
            title?.includes("step") ||
            original_title?.includes("step") ||
            name?.includes("vintage") ||
            original_name?.includes("vintage") ||
            title?.includes("vintage") ||
            original_title?.includes("vintage") ||
            name?.includes("beach") ||
            original_name?.includes("beach") ||
            title?.includes("beach") ||
            original_title?.includes("beach") ||
            name?.includes("massage") ||
            original_name?.includes("massage") ||
            title?.includes("massage") ||
            original_title?.includes("massage") ||
            name?.includes("love") ||
            original_name?.includes("love") ||
            title?.includes("love") ||
            original_title?.includes("love") ||
            name?.includes("tight") ||
            original_name?.includes("tight") ||
            title?.includes("tight") ||
            original_title?.includes("tight") ||
            name?.includes("feeling") ||
            original_name?.includes("feeling") ||
            title?.includes("feeling") ||
            original_title?.includes("feeling") ||
            name?.includes("heart") ||
            original_name?.includes("heart") ||
            title?.includes("heart") ||
            original_title?.includes("heart") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("pretty") ||
            original_name?.includes("pretty") ||
            title?.includes("pretty") ||
            original_title?.includes("pretty") ||
            name?.includes("high school") ||
            original_name?.includes("high school") ||
            title?.includes("high school") ||
            original_title?.includes("high school") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("girl") ||
            original_name?.includes("girl") ||
            title?.includes("girl") ||
            original_title?.includes("girl") ||
            name?.includes("boy") ||
            original_name?.includes("boy") ||
            title?.includes("boy") ||
            original_title?.includes("boy") ||
            name?.includes("friend") ||
            original_name?.includes("friend") ||
            title?.includes("friend") ||
            original_title?.includes("friend") ||
            name?.includes("x") ||
            original_name?.includes("x") ||
            title?.includes("x") ||
            original_title?.includes("x") ||
            name?.includes("fu") ||
            original_name?.includes("fu") ||
            title?.includes("fu") ||
            original_title?.includes("fu") ||
            name?.includes("f*") ||
            original_name?.includes("f*") ||
            title?.includes("f*") ||
            original_title?.includes("f*") ||
            name?.includes("san") ||
            original_name?.includes("san") ||
            title?.includes("san") ||
            original_title?.includes("san") ||
            name?.includes("whore") ||
            original_name?.includes("whore") ||
            title?.includes("whore") ||
            original_title?.includes("whore") ||
            name?.includes("revolver") ||
            original_name?.includes("revolver") ||
            title?.includes("revolver") ||
            original_title?.includes("revolver")
        ) {
            searchMedia.results.splice(index, 1);
        }
    });
}

/****************************************************************************/
/***************************ForbiddenMultiSearch*********************************/
/****************************************************************************/
export function ForbiddenMultiSearch(
    multiSearch: {
        page: number;
        results: {
            adult: boolean;
            backdrop_path: string;
            genre_ids: number[];
            id: number;
            original_language: string;
            original_title: string;
            overview: string;
            popularity: number;
            poster_path: string;
            release_date: string;
            title: string;
            video: boolean;
            vote_average: number;
            vote_count: number;
            // tv
            first_air_date: string;
            name: string;
            origin_country: string;
            original_name: string;
            //
            media_type: string;
            // people
            gender: number;
            known_for_department: string;
            profile_path: string;
        }[];
        total_pages: number;
        total_results: number;
    } | null
) {
    multiSearch?.results.forEach((media, index) => {
        const name = media?.name?.toLowerCase();
        const original_name = media?.original_name?.toLowerCase();
        const title = media?.title?.toLowerCase();
        const original_title = media?.original_title?.toLowerCase();

        // Removing +18content
        if (
            // Filtering media && People
            name?.includes("sex") ||
            original_name?.includes("sex") ||
            title?.includes("sex") ||
            original_title?.includes("sex") ||
            name?.includes("horny") ||
            original_name?.includes("horny") ||
            title?.includes("horny") ||
            original_title?.includes("horny") ||
            name?.includes("tit") ||
            original_name?.includes("tit") ||
            title?.includes("tit") ||
            original_title?.includes("tit") ||
            name?.includes("boob") ||
            original_name?.includes("boob") ||
            title?.includes("boob") ||
            original_title?.includes("boob") ||
            name?.includes("hentai") ||
            original_name?.includes("hentai") ||
            title?.includes("hentai") ||
            original_title?.includes("hentai") ||
            name?.includes("fuck") ||
            original_name?.includes("fuck") ||
            title?.includes("fuck") ||
            original_title?.includes("fuck") ||
            name?.includes("porn") ||
            original_name?.includes("porn") ||
            title?.includes("porn") ||
            original_title?.includes("porn") ||
            name?.includes("gay") ||
            original_name?.includes("gay") ||
            title?.includes("gay") ||
            original_title?.includes("gay") ||
            name?.includes("lesbian") ||
            original_name?.includes("lesbian") ||
            title?.includes("lesbian") ||
            original_title?.includes("lesbian") ||
            name?.includes("ass") ||
            original_name?.includes("ass") ||
            title?.includes("ass") ||
            original_title?.includes("ass") ||
            name?.includes("orgasm") ||
            original_name?.includes("orgasm") ||
            title?.includes("orgasm") ||
            original_title?.includes("orgasm") ||
            name?.includes("virgin") ||
            original_name?.includes("virgin") ||
            title?.includes("virgin") ||
            original_title?.includes("virgin") ||
            name?.includes("18") ||
            original_name?.includes("18") ||
            title?.includes("18") ||
            original_title?.includes("18") ||
            name?.includes("16") ||
            original_name?.includes("16") ||
            title?.includes("16") ||
            original_title?.includes("16") ||
            name?.includes("transgender") ||
            original_name?.includes("transgender") ||
            title?.includes("transgender") ||
            original_title?.includes("transgender") ||
            name?.includes("mature") ||
            original_name?.includes("mature") ||
            title?.includes("mature") ||
            original_title?.includes("mature") ||
            name?.includes("milf") ||
            original_name?.includes("milf") ||
            title?.includes("milf") ||
            original_title?.includes("milf") ||
            name?.includes("orgy") ||
            original_name?.includes("orgy") ||
            title?.includes("orgy") ||
            original_title?.includes("orgy") ||
            name?.includes("cosplay") ||
            original_name?.includes("cosplay") ||
            title?.includes("cosplay") ||
            original_title?.includes("cosplay") ||
            name?.includes("squirt") ||
            original_name?.includes("squirt") ||
            title?.includes("squirt") ||
            original_title?.includes("squirt") ||
            name?.includes("brunette") ||
            original_name?.includes("brunette") ||
            title?.includes("brunette") ||
            original_title?.includes("brunette") ||
            name?.includes("handjob") ||
            original_name?.includes("handjob") ||
            title?.includes("handjob") ||
            original_title?.includes("handjob") ||
            name?.includes("cum") ||
            original_name?.includes("cum") ||
            title?.includes("cum") ||
            original_title?.includes("cum") ||
            name?.includes("blowjob") ||
            original_name?.includes("blowjob") ||
            title?.includes("blowjob") ||
            original_title?.includes("blowjob") ||
            name?.includes("hardcore") ||
            original_name?.includes("hardcore") ||
            title?.includes("hardcore") ||
            original_title?.includes("hardcore") ||
            name?.includes("tatto") ||
            original_name?.includes("tatto") ||
            title?.includes("tatto") ||
            original_title?.includes("tatto") ||
            name?.includes("pussy") ||
            original_name?.includes("pussy") ||
            title?.includes("pussy") ||
            original_title?.includes("pussy") ||
            name?.includes("fisting") ||
            original_name?.includes("fisting") ||
            title?.includes("fisting") ||
            original_title?.includes("fisting") ||
            name?.includes("strap") ||
            original_name?.includes("strap") ||
            title?.includes("strap") ||
            original_title?.includes("strap") ||
            name?.includes("creampie") ||
            original_name?.includes("creampie") ||
            title?.includes("creampie") ||
            original_title?.includes("creampie") ||
            name?.includes("gangbang") ||
            original_name?.includes("gangbang") ||
            title?.includes("gangbang") ||
            original_title?.includes("gangbang") ||
            name?.includes("female") ||
            original_name?.includes("female") ||
            title?.includes("female") ||
            original_title?.includes("female") ||
            name?.includes("threesome") ||
            original_name?.includes("threesome") ||
            title?.includes("threesome") ||
            original_title?.includes("threesome") ||
            name?.includes("step") ||
            original_name?.includes("step") ||
            title?.includes("step") ||
            original_title?.includes("step") ||
            name?.includes("vintage") ||
            original_name?.includes("vintage") ||
            title?.includes("vintage") ||
            original_title?.includes("vintage") ||
            name?.includes("beach") ||
            original_name?.includes("beach") ||
            title?.includes("beach") ||
            original_title?.includes("beach") ||
            name?.includes("massage") ||
            original_name?.includes("massage") ||
            title?.includes("massage") ||
            original_title?.includes("massage") ||
            name?.includes("love") ||
            original_name?.includes("love") ||
            title?.includes("love") ||
            original_title?.includes("love") ||
            name?.includes("tight") ||
            original_name?.includes("tight") ||
            title?.includes("tight") ||
            original_title?.includes("tight") ||
            name?.includes("feeling") ||
            original_name?.includes("feeling") ||
            title?.includes("feeling") ||
            original_title?.includes("feeling") ||
            name?.includes("heart") ||
            original_name?.includes("heart") ||
            title?.includes("heart") ||
            original_title?.includes("heart") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("pretty") ||
            original_name?.includes("pretty") ||
            title?.includes("pretty") ||
            original_title?.includes("pretty") ||
            name?.includes("high school") ||
            original_name?.includes("high school") ||
            title?.includes("high school") ||
            original_title?.includes("high school") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("girl") ||
            original_name?.includes("girl") ||
            title?.includes("girl") ||
            original_title?.includes("girl") ||
            name?.includes("boy") ||
            original_name?.includes("boy") ||
            title?.includes("boy") ||
            original_title?.includes("boy") ||
            name?.includes("friend") ||
            original_name?.includes("friend") ||
            title?.includes("friend") ||
            original_title?.includes("friend") ||
            name?.includes("x") ||
            original_name?.includes("x") ||
            title?.includes("x") ||
            original_title?.includes("x") ||
            name?.includes("fu") ||
            original_name?.includes("fu") ||
            title?.includes("fu") ||
            original_title?.includes("fu") ||
            name?.includes("f*") ||
            original_name?.includes("f*") ||
            title?.includes("f*") ||
            original_title?.includes("f*") ||
            name?.includes("san") ||
            original_name?.includes("san") ||
            title?.includes("san") ||
            original_title?.includes("san") ||
            name?.includes("whore") ||
            original_name?.includes("whore") ||
            title?.includes("whore") ||
            original_title?.includes("whore") ||
            name?.includes("revolver") ||
            original_name?.includes("revolver") ||
            title?.includes("revolver") ||
            original_title?.includes("revolver")
        ) {
            multiSearch.results.splice(index, 1);
        }
    });
}

/****************************************************************************/
/***************************ForbiddenPersonMedia*********************************/
/****************************************************************************/
export function ForbiddenPersonMedia(personMedia: {
    cast: {
        adult: boolean;
        backdrop_path: string;
        genre_ids: number[];
        id: number;
        original_language: string;
        original_title: string;
        overview: string;
        popularity: number;
        poster_path: string;
        release_date: string;
        title: string;
        video: boolean;
        vote_average: number;
        vote_count: number;
        character: string;
        credit_id: string;
        order: number;
        // tv
        origin_country: string[];
        original_name: string;
        first_air_date: string;
        name: string;
        episode_count: number;
    }[];
    crew: {
        adult: boolean;
        backdrop_path: string;
        genre_ids: number[];
        id: number;
        original_language: string;
        original_title: string;
        overview: string;
        popularity: number;
        poster_path: string;
        release_date: string;
        title: string;
        video: boolean;
        vote_average: number;
        vote_count: number;
        credit_id: string;
        department: string;
        job: string;
        // tv
        origin_country: string[];
        original_name: string;
        first_air_date: string;
        name: string;
        episode_count: number;
    }[];
    id: number;
}) {
    personMedia.cast.forEach((media, index) => {
        const name = media?.name?.toLowerCase();
        const original_name = media?.original_name?.toLowerCase();
        const title = media?.title?.toLowerCase();
        const original_title = media?.original_title?.toLowerCase();

        // Removing +18content
        if (
            // Filtering media && People
            name?.includes("sex") ||
            original_name?.includes("sex") ||
            title?.includes("sex") ||
            original_title?.includes("sex") ||
            name?.includes("horny") ||
            original_name?.includes("horny") ||
            title?.includes("horny") ||
            original_title?.includes("horny") ||
            name?.includes("tit") ||
            original_name?.includes("tit") ||
            title?.includes("tit") ||
            original_title?.includes("tit") ||
            name?.includes("boob") ||
            original_name?.includes("boob") ||
            title?.includes("boob") ||
            original_title?.includes("boob") ||
            name?.includes("hentai") ||
            original_name?.includes("hentai") ||
            title?.includes("hentai") ||
            original_title?.includes("hentai") ||
            name?.includes("fuck") ||
            original_name?.includes("fuck") ||
            title?.includes("fuck") ||
            original_title?.includes("fuck") ||
            name?.includes("porn") ||
            original_name?.includes("porn") ||
            title?.includes("porn") ||
            original_title?.includes("porn") ||
            name?.includes("gay") ||
            original_name?.includes("gay") ||
            title?.includes("gay") ||
            original_title?.includes("gay") ||
            name?.includes("lesbian") ||
            original_name?.includes("lesbian") ||
            title?.includes("lesbian") ||
            original_title?.includes("lesbian") ||
            name?.includes("ass") ||
            original_name?.includes("ass") ||
            title?.includes("ass") ||
            original_title?.includes("ass") ||
            name?.includes("orgasm") ||
            original_name?.includes("orgasm") ||
            title?.includes("orgasm") ||
            original_title?.includes("orgasm") ||
            name?.includes("virgin") ||
            original_name?.includes("virgin") ||
            title?.includes("virgin") ||
            original_title?.includes("virgin") ||
            name?.includes("18") ||
            original_name?.includes("18") ||
            title?.includes("18") ||
            original_title?.includes("18") ||
            name?.includes("16") ||
            original_name?.includes("16") ||
            title?.includes("16") ||
            original_title?.includes("16") ||
            name?.includes("transgender") ||
            original_name?.includes("transgender") ||
            title?.includes("transgender") ||
            original_title?.includes("transgender") ||
            name?.includes("mature") ||
            original_name?.includes("mature") ||
            title?.includes("mature") ||
            original_title?.includes("mature") ||
            name?.includes("milf") ||
            original_name?.includes("milf") ||
            title?.includes("milf") ||
            original_title?.includes("milf") ||
            name?.includes("orgy") ||
            original_name?.includes("orgy") ||
            title?.includes("orgy") ||
            original_title?.includes("orgy") ||
            name?.includes("cosplay") ||
            original_name?.includes("cosplay") ||
            title?.includes("cosplay") ||
            original_title?.includes("cosplay") ||
            name?.includes("squirt") ||
            original_name?.includes("squirt") ||
            title?.includes("squirt") ||
            original_title?.includes("squirt") ||
            name?.includes("brunette") ||
            original_name?.includes("brunette") ||
            title?.includes("brunette") ||
            original_title?.includes("brunette") ||
            name?.includes("handjob") ||
            original_name?.includes("handjob") ||
            title?.includes("handjob") ||
            original_title?.includes("handjob") ||
            name?.includes("cum") ||
            original_name?.includes("cum") ||
            title?.includes("cum") ||
            original_title?.includes("cum") ||
            name?.includes("blowjob") ||
            original_name?.includes("blowjob") ||
            title?.includes("blowjob") ||
            original_title?.includes("blowjob") ||
            name?.includes("hardcore") ||
            original_name?.includes("hardcore") ||
            title?.includes("hardcore") ||
            original_title?.includes("hardcore") ||
            name?.includes("tatto") ||
            original_name?.includes("tatto") ||
            title?.includes("tatto") ||
            original_title?.includes("tatto") ||
            name?.includes("pussy") ||
            original_name?.includes("pussy") ||
            title?.includes("pussy") ||
            original_title?.includes("pussy") ||
            name?.includes("fisting") ||
            original_name?.includes("fisting") ||
            title?.includes("fisting") ||
            original_title?.includes("fisting") ||
            name?.includes("strap") ||
            original_name?.includes("strap") ||
            title?.includes("strap") ||
            original_title?.includes("strap") ||
            name?.includes("creampie") ||
            original_name?.includes("creampie") ||
            title?.includes("creampie") ||
            original_title?.includes("creampie") ||
            name?.includes("gangbang") ||
            original_name?.includes("gangbang") ||
            title?.includes("gangbang") ||
            original_title?.includes("gangbang") ||
            name?.includes("female") ||
            original_name?.includes("female") ||
            title?.includes("female") ||
            original_title?.includes("female") ||
            name?.includes("threesome") ||
            original_name?.includes("threesome") ||
            title?.includes("threesome") ||
            original_title?.includes("threesome") ||
            name?.includes("step") ||
            original_name?.includes("step") ||
            title?.includes("step") ||
            original_title?.includes("step") ||
            name?.includes("vintage") ||
            original_name?.includes("vintage") ||
            title?.includes("vintage") ||
            original_title?.includes("vintage") ||
            name?.includes("beach") ||
            original_name?.includes("beach") ||
            title?.includes("beach") ||
            original_title?.includes("beach") ||
            name?.includes("massage") ||
            original_name?.includes("massage") ||
            title?.includes("massage") ||
            original_title?.includes("massage") ||
            name?.includes("love") ||
            original_name?.includes("love") ||
            title?.includes("love") ||
            original_title?.includes("love") ||
            name?.includes("tight") ||
            original_name?.includes("tight") ||
            title?.includes("tight") ||
            original_title?.includes("tight") ||
            name?.includes("feeling") ||
            original_name?.includes("feeling") ||
            title?.includes("feeling") ||
            original_title?.includes("feeling") ||
            name?.includes("heart") ||
            original_name?.includes("heart") ||
            title?.includes("heart") ||
            original_title?.includes("heart") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("pretty") ||
            original_name?.includes("pretty") ||
            title?.includes("pretty") ||
            original_title?.includes("pretty") ||
            name?.includes("high school") ||
            original_name?.includes("high school") ||
            title?.includes("high school") ||
            original_title?.includes("high school") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("girl") ||
            original_name?.includes("girl") ||
            title?.includes("girl") ||
            original_title?.includes("girl") ||
            name?.includes("boy") ||
            original_name?.includes("boy") ||
            title?.includes("boy") ||
            original_title?.includes("boy") ||
            name?.includes("friend") ||
            original_name?.includes("friend") ||
            title?.includes("friend") ||
            original_title?.includes("friend") ||
            name?.includes("x") ||
            original_name?.includes("x") ||
            title?.includes("x") ||
            original_title?.includes("x") ||
            name?.includes("fu") ||
            original_name?.includes("fu") ||
            title?.includes("fu") ||
            original_title?.includes("fu") ||
            name?.includes("f*") ||
            original_name?.includes("f*") ||
            title?.includes("f*") ||
            original_title?.includes("f*") ||
            name?.includes("san") ||
            original_name?.includes("san") ||
            title?.includes("san") ||
            original_title?.includes("san") ||
            name?.includes("whore") ||
            original_name?.includes("whore") ||
            title?.includes("whore") ||
            original_title?.includes("whore") ||
            name?.includes("revolver") ||
            original_name?.includes("revolver") ||
            title?.includes("revolver") ||
            original_title?.includes("revolver")
        ) {
            personMedia.cast.splice(index, 1);
        }
    });

    personMedia.crew.forEach((media, index) => {
        const name = media?.name?.toLowerCase();
        const original_name = media?.original_name?.toLowerCase();
        const title = media?.title?.toLowerCase();
        const original_title = media?.original_title?.toLowerCase();

        // Removing +18content
        if (
            // Filtering media && People
            name?.includes("sex") ||
            original_name?.includes("sex") ||
            title?.includes("sex") ||
            original_title?.includes("sex") ||
            name?.includes("horny") ||
            original_name?.includes("horny") ||
            title?.includes("horny") ||
            original_title?.includes("horny") ||
            name?.includes("tit") ||
            original_name?.includes("tit") ||
            title?.includes("tit") ||
            original_title?.includes("tit") ||
            name?.includes("boob") ||
            original_name?.includes("boob") ||
            title?.includes("boob") ||
            original_title?.includes("boob") ||
            name?.includes("hentai") ||
            original_name?.includes("hentai") ||
            title?.includes("hentai") ||
            original_title?.includes("hentai") ||
            name?.includes("fuck") ||
            original_name?.includes("fuck") ||
            title?.includes("fuck") ||
            original_title?.includes("fuck") ||
            name?.includes("porn") ||
            original_name?.includes("porn") ||
            title?.includes("porn") ||
            original_title?.includes("porn") ||
            name?.includes("gay") ||
            original_name?.includes("gay") ||
            title?.includes("gay") ||
            original_title?.includes("gay") ||
            name?.includes("lesbian") ||
            original_name?.includes("lesbian") ||
            title?.includes("lesbian") ||
            original_title?.includes("lesbian") ||
            name?.includes("ass") ||
            original_name?.includes("ass") ||
            title?.includes("ass") ||
            original_title?.includes("ass") ||
            name?.includes("orgasm") ||
            original_name?.includes("orgasm") ||
            title?.includes("orgasm") ||
            original_title?.includes("orgasm") ||
            name?.includes("virgin") ||
            original_name?.includes("virgin") ||
            title?.includes("virgin") ||
            original_title?.includes("virgin") ||
            name?.includes("18") ||
            original_name?.includes("18") ||
            title?.includes("18") ||
            original_title?.includes("18") ||
            name?.includes("16") ||
            original_name?.includes("16") ||
            title?.includes("16") ||
            original_title?.includes("16") ||
            name?.includes("transgender") ||
            original_name?.includes("transgender") ||
            title?.includes("transgender") ||
            original_title?.includes("transgender") ||
            name?.includes("mature") ||
            original_name?.includes("mature") ||
            title?.includes("mature") ||
            original_title?.includes("mature") ||
            name?.includes("milf") ||
            original_name?.includes("milf") ||
            title?.includes("milf") ||
            original_title?.includes("milf") ||
            name?.includes("orgy") ||
            original_name?.includes("orgy") ||
            title?.includes("orgy") ||
            original_title?.includes("orgy") ||
            name?.includes("cosplay") ||
            original_name?.includes("cosplay") ||
            title?.includes("cosplay") ||
            original_title?.includes("cosplay") ||
            name?.includes("squirt") ||
            original_name?.includes("squirt") ||
            title?.includes("squirt") ||
            original_title?.includes("squirt") ||
            name?.includes("brunette") ||
            original_name?.includes("brunette") ||
            title?.includes("brunette") ||
            original_title?.includes("brunette") ||
            name?.includes("handjob") ||
            original_name?.includes("handjob") ||
            title?.includes("handjob") ||
            original_title?.includes("handjob") ||
            name?.includes("cum") ||
            original_name?.includes("cum") ||
            title?.includes("cum") ||
            original_title?.includes("cum") ||
            name?.includes("blowjob") ||
            original_name?.includes("blowjob") ||
            title?.includes("blowjob") ||
            original_title?.includes("blowjob") ||
            name?.includes("hardcore") ||
            original_name?.includes("hardcore") ||
            title?.includes("hardcore") ||
            original_title?.includes("hardcore") ||
            name?.includes("tatto") ||
            original_name?.includes("tatto") ||
            title?.includes("tatto") ||
            original_title?.includes("tatto") ||
            name?.includes("pussy") ||
            original_name?.includes("pussy") ||
            title?.includes("pussy") ||
            original_title?.includes("pussy") ||
            name?.includes("fisting") ||
            original_name?.includes("fisting") ||
            title?.includes("fisting") ||
            original_title?.includes("fisting") ||
            name?.includes("strap") ||
            original_name?.includes("strap") ||
            title?.includes("strap") ||
            original_title?.includes("strap") ||
            name?.includes("creampie") ||
            original_name?.includes("creampie") ||
            title?.includes("creampie") ||
            original_title?.includes("creampie") ||
            name?.includes("gangbang") ||
            original_name?.includes("gangbang") ||
            title?.includes("gangbang") ||
            original_title?.includes("gangbang") ||
            name?.includes("female") ||
            original_name?.includes("female") ||
            title?.includes("female") ||
            original_title?.includes("female") ||
            name?.includes("threesome") ||
            original_name?.includes("threesome") ||
            title?.includes("threesome") ||
            original_title?.includes("threesome") ||
            name?.includes("step") ||
            original_name?.includes("step") ||
            title?.includes("step") ||
            original_title?.includes("step") ||
            name?.includes("vintage") ||
            original_name?.includes("vintage") ||
            title?.includes("vintage") ||
            original_title?.includes("vintage") ||
            name?.includes("beach") ||
            original_name?.includes("beach") ||
            title?.includes("beach") ||
            original_title?.includes("beach") ||
            name?.includes("massage") ||
            original_name?.includes("massage") ||
            title?.includes("massage") ||
            original_title?.includes("massage") ||
            name?.includes("love") ||
            original_name?.includes("love") ||
            title?.includes("love") ||
            original_title?.includes("love") ||
            name?.includes("tight") ||
            original_name?.includes("tight") ||
            title?.includes("tight") ||
            original_title?.includes("tight") ||
            name?.includes("feeling") ||
            original_name?.includes("feeling") ||
            title?.includes("feeling") ||
            original_title?.includes("feeling") ||
            name?.includes("heart") ||
            original_name?.includes("heart") ||
            title?.includes("heart") ||
            original_title?.includes("heart") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("pretty") ||
            original_name?.includes("pretty") ||
            title?.includes("pretty") ||
            original_title?.includes("pretty") ||
            name?.includes("high school") ||
            original_name?.includes("high school") ||
            title?.includes("high school") ||
            original_title?.includes("high school") ||
            name?.includes("kiss") ||
            original_name?.includes("kiss") ||
            title?.includes("kiss") ||
            original_title?.includes("kiss") ||
            name?.includes("girl") ||
            original_name?.includes("girl") ||
            title?.includes("girl") ||
            original_title?.includes("girl") ||
            name?.includes("boy") ||
            original_name?.includes("boy") ||
            title?.includes("boy") ||
            original_title?.includes("boy") ||
            name?.includes("friend") ||
            original_name?.includes("friend") ||
            title?.includes("friend") ||
            original_title?.includes("friend") ||
            name?.includes("x") ||
            original_name?.includes("x") ||
            title?.includes("x") ||
            original_title?.includes("x") ||
            name?.includes("fu") ||
            original_name?.includes("fu") ||
            title?.includes("fu") ||
            original_title?.includes("fu") ||
            name?.includes("f*") ||
            original_name?.includes("f*") ||
            title?.includes("f*") ||
            original_title?.includes("f*") ||
            name?.includes("san") ||
            original_name?.includes("san") ||
            title?.includes("san") ||
            original_title?.includes("san") ||
            name?.includes("whore") ||
            original_name?.includes("whore") ||
            title?.includes("whore") ||
            original_title?.includes("whore") ||
            name?.includes("revolver") ||
            original_name?.includes("revolver") ||
            title?.includes("revolver") ||
            original_title?.includes("revolver")
        ) {
            personMedia.crew.splice(index, 1);
        }
    });
}
